package config

import (
	"fmt"
	"os"
	"strings"

	"github.com/joho/godotenv"
	"github.com/local/swarm/orchestrator/internal/llm"
)

type Config struct {
	MainnetRPC    string
	LLMBaseURL    string
	LLMKey        string
	LLMModel      string
	SwarmPrivKey  string
	OGRpcURL      string
	OGPrivateKey  string
	OGINFTAddress string
	ReportServerBaseURL    string
	StorageGatewayURL      string

	// 0G Compute / sealed inference — optional second provider
	SealedLLMBaseURL string
	SealedLLMKey     string
	SealedLLMModel   string
}

func Load() (*Config, error) {
	_ = godotenv.Load("../../.env")

	// Default LLM (general tasks)
	llmKey := firstEnv("LLM_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY")
	baseURL := os.Getenv("LLM_BASE_URL")
	if baseURL == "" {
		baseURL = detectBaseURL(llmKey)
	}
	model := os.Getenv("LLM_MODEL")

	// Sealed LLM (sensitive tasks, e.g. 0G Compute TEE)
	sealedKey := firstEnv("SEALED_LLM_API_KEY", "ZG_API_SECRET")
	sealedURL := firstEnvValue("SEALED_LLM_BASE_URL", "ZG_SERVICE_URL")
	sealedModel := os.Getenv("SEALED_LLM_MODEL")

	c := &Config{
		MainnetRPC:          os.Getenv("MAINNET_RPC_URL"),
		LLMBaseURL:          baseURL,
		LLMKey:              llmKey,
		LLMModel:            model,
		SwarmPrivKey:        os.Getenv("SWARM_PRIVATE_KEY"),
		OGRpcURL:            os.Getenv("OG_RPC_URL"),
		OGPrivateKey:        os.Getenv("OG_PRIVATE_KEY"),
		OGINFTAddress:       os.Getenv("OG_INFT_ADDRESS"),
		ReportServerBaseURL:    os.Getenv("REPORT_SERVER_BASE_URL"),
		StorageGatewayURL:      os.Getenv("STORAGE_GATEWAY_URL"),
		SealedLLMBaseURL:    sealedURL,
		SealedLLMKey:        sealedKey,
		SealedLLMModel:      sealedModel,
	}

	if c.MainnetRPC == "" {
		return nil, fmt.Errorf("MAINNET_RPC_URL not set")
	}
	if c.LLMKey == "" {
		return nil, fmt.Errorf("no LLM API key found (set LLM_API_KEY, OPENAI_API_KEY, or ANTHROPIC_API_KEY)")
	}

	return c, nil
}

// BuildLLMRegistry creates a client registry from config.
func (c *Config) BuildLLMRegistry() *llm.Registry {
	provider := detectProvider(c.LLMBaseURL, c.LLMKey)
	defaultClient := llm.NewOpenAICompatibleClientWithProvider(c.LLMBaseURL, c.LLMKey, c.LLMModel, provider)

	reg := &llm.Registry{Default: defaultClient}

	if c.SealedLLMBaseURL != "" && c.SealedLLMKey != "" {
		sealedProvider := detectProvider(c.SealedLLMBaseURL, c.SealedLLMKey)
		reg.Sealed = llm.NewOpenAICompatibleClientWithProvider(
			c.SealedLLMBaseURL,
			c.SealedLLMKey,
			c.SealedLLMModel,
			sealedProvider,
		)
	}

	return reg
}

func firstEnv(keys ...string) string {
	for _, k := range keys {
		if v := os.Getenv(k); v != "" {
			return v
		}
	}
	return ""
}

func firstEnvValue(keys ...string) string {
	for _, k := range keys {
		if v := os.Getenv(k); v != "" {
			return v
		}
	}
	return ""
}

func detectBaseURL(apiKey string) string {
	if strings.HasPrefix(apiKey, "sk-ant-") {
		return "https://api.anthropic.com/v1"
	}
	if strings.HasPrefix(apiKey, "sk-") {
		return "https://api.openai.com/v1"
	}
	if strings.HasPrefix(apiKey, "app-sk-") {
		// 0G Compute secret generated by CLI
		if url := os.Getenv("ZG_SERVICE_URL"); url != "" {
			return url + "/v1/proxy"
		}
	}
	return "https://api.openai.com/v1"
}

func detectProvider(baseURL, apiKey string) llm.Provider {
	if strings.Contains(baseURL, "0g") || strings.HasPrefix(apiKey, "app-sk-") {
		return llm.ProviderZeroG
	}
	if strings.Contains(baseURL, "anthropic") || strings.HasPrefix(apiKey, "sk-ant-") {
		return llm.ProviderAnthropic
	}
	if strings.Contains(baseURL, "openrouter") {
		return llm.ProviderOpenRouter
	}
	if strings.Contains(baseURL, "chutes") {
		return llm.ProviderChutes
	}
	if strings.Contains(baseURL, "localhost") || strings.Contains(baseURL, "127.0.0.1") {
		return llm.ProviderOllama
	}
	if strings.Contains(baseURL, "openai") && strings.HasPrefix(apiKey, "sk-") {
		return llm.ProviderOpenAI
	}
	return llm.ProviderCustom
}
