/**
 * Anchor integration test scaffold for VulnerableVault.
 *
 * These tests verify the program deploys successfully.
 * The actual vulnerability demonstrations live in poc/exploit.ts.
 *
 * Run: anchor test
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, LAMPORTS_PER_SOL } from "@solana/web3.js";
import { assert } from "chai";

// IDL is generated by `anchor build` — import at runtime so the file
// can be checked into git without the build artifact.
const PROGRAM_ID = new PublicKey("VuLnVauLt111111111111111111111111111111111");

describe("vulnerable-vault", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  it("program is deployed and reachable", async () => {
    const info = await provider.connection.getAccountInfo(PROGRAM_ID);
    // If the program is not deployed we skip rather than fail hard,
    // so the test suite can still run in CI without a live validator.
    if (!info) {
      console.log("  Program not deployed — skipping live checks");
      return;
    }
    assert.ok(info.executable, "Program account should be executable");
  });

  it("vault PDA can be derived", async () => {
    const authority = provider.wallet.publicKey;
    const [vaultPda, bump] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), authority.toBuffer()],
      PROGRAM_ID
    );
    assert.ok(vaultPda instanceof PublicKey);
    assert.ok(bump >= 0 && bump <= 255);
    console.log(`  Vault PDA: ${vaultPda.toBase58()} (bump=${bump})`);
  });
});
